Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello > /tmp/hello.txt"

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
  end
end